version: '3.1'
services:

    sql_server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sql_server
        ports:
            - 1433:1433
        networks:
            - back
        environment:
            SA_PASSWORD: MySecretPassword!
            ACCEPT_EULA: "Y"

    rabbitmq:
        image: rabbitmq:3.11.10-management
        container_name: rabbitmq
        restart: on-failure
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - back
        environment:
            - "RABBITMQ_DEFAULT_USER=guest"
            - "RABBITMQ_DEFAULT_PASS=guest"

networks:
    back:
        driver: bridge