version: '3.1'
services:

    sql_server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sql_server
        ports:
            - 1433:1433
        networks:
            - back
        environment:
            SA_PASSWORD: ${SA_PASSWORD}
            ACCEPT_EULA: "Y"
        volumes:
            - ./mssql:/var/opt/mssql

    rabbitmq:
        image: rabbitmq:3.11.10-management
        container_name: rabbitmq
        restart: on-failure
        ports:
            - 5672:5672
        networks:
            - back
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USERNAME}
            - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}

networks:
    back:
        driver: bridge

volumes:
    esdata-staging:
        driver: local